export const ADMIN_SIDEBAR_MENU = [
  { key: 'dashboard', label: 'Dashboard', icon: 'grid', path: '/admin' },
  { key: 'bundles', label: 'Bundles', icon: 'cube', path: '/admin/bundles' },
  { key: 'vouchers', label: 'Vouchers', icon: 'ticket', path: '/admin/vouchers' },
  { key: 'transactions', label: 'Transactions', icon: 'swap', path: '/admin/transactions' },
  { key: 'withdraw', label: 'Withdraw', icon: 'wallet', path: '/admin/withdraw' },
  { key: 'reports', label: 'Reports', icon: 'chart', path: '/admin/reports' },
  { key: 'clients', label: 'Clients', icon: 'users', path: '/admin/clients' },
  { key: 'agents', label: 'Agents', icon: 'userPlus', path: '/admin/agents' },
  {
    key: 'mikrotikRouters',
    label: 'MikroTik Routers',
    icon: 'router',
    spacerBefore: true,
    dividerAfter: true,
    path: '/admin/mikrotik-routers',
  },
  { key: 'routerStatus', label: 'Router Status', icon: 'status', locked: true, path: '/admin/router-status' },
  {
    key: 'hotspotProfiles',
    label: 'Hotspot Profiles',
    icon: 'hotspot',
    locked: true,
    path: '/admin/hotspot-profiles',
  },
  {
    key: 'generateVouchers',
    label: 'Generate Vouchers',
    icon: 'magic',
    locked: true,
    path: '/admin/generate-vouchers',
  },
  {
    key: 'mikrotikVouchers',
    label: 'MikroTik Vouchers',
    icon: 'ticket',
    locked: true,
    path: '/admin/mikrotik-vouchers',
  },
  {
    key: 'hotspotPageGenerator',
    label: 'Hotspot Page Generator',
    icon: 'page',
    spacerBefore: true,
    locked: true,
    path: '/admin/hotspot-page-generator',
  },
  { key: 'activeSessions', label: 'Active Sessions', icon: 'sessions', locked: true, path: '/admin/active-sessions' },
  { key: 'myProfile', label: 'My Profile', icon: 'profile', path: '/admin/my-profile' },
  { key: 'logout', label: 'Logout', icon: 'logout', path: '/admin/logout' },
];
